# nixpacks.toml

# Define the setup phase
[phases.setup]
# List Nix packages required for the build environment.
# python311 includes the venv module, git is needed for cloning.
nixPkgs = ["python311", "git"]

# Define the install phase
[phases.install]
# Commands to run for installing dependencies.
cmds = [
  # Create a virtual environment named 'venv' explicitly inside /app.
  "python3 -m venv /app/venv",
  # Use the absolute path to pip within the created venv to install packages.
  "/app/venv/bin/pip install -r requirements.txt"
]
# Specify directories to cache between builds.
# Caching pip downloads is generally safe. Let's avoid caching the venv directory for now.
cacheDirectories = ["/root/.cache/pip"]

# Define the start phase
[start]
# The command to run the application.
# Use absolute paths to ensure the interpreter and script are found correctly,
# regardless of the runtime working directory.
cmd = "/app/venv/bin/python /app/bot.py"

