# nixpacks.toml

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "git"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "python bot.py"
