# nixpacks.toml

[variables]
NIXPACKS_METADATA = "python"
PIP_DEFAULT_TIMEOUT = "100"
PIP_DISABLE_PIP_VERSION_CHECK = "1"
PIP_NO_CACHE_DIR = "1"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONFAULTHANDLER = "1"
PYTHONHASHSEED = "random"
PYTHONUNBUFFERED = "1"

[phases.setup]
nixPkgs = [
    "python3",
    "gcc",
    "parallel"
]
nixLibs = [
    "zlib",
    "stdenv.cc.cc.lib"
]
nixpkgsArchive = "bf446f08bff6814b569265bef8374cfdd3d8f0e0"

[phases.install]
dependsOn = ["setup"]
cmds = [
    "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"
]
cacheDirectories = ["/root/.cache/pip"]
paths = ["/opt/venv/bin"]

[phases.build]
cmds = [
    "chmod +x bot.py"
]

[start]
cmd = "/opt/venv/bin/python bot.py"
