# nixpacks.toml

[phases.setup]
nixPkgs = ["python311", "python311Packages.venv", "git"]

[phases.install]
cmds = [
  "python3 -m venv venv",
  "./venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "./venv/bin/python bot.py"
